name: humanrl
channels:
- pkgw-forge
- loopbio
- conda-forge
- defaults
dependencies:
- blas=1.1=openblas
- bzip2=1.0.6=1
- cairo=1.14.6=4
- cycler=0.10.0=py35_0
- dbus=1.10.10=3
- expat=2.1.0=2
- ffmpeg=3.2.4=1
- fontconfig=2.12.1=4
- freetype=2.7=1
- gettext=0.19.7=1
- giflib=5.1.4=0
- glib=2.51.4=0
- gobject-introspection=1.51.3=py35_0
- graphite2=1.3.9=0
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=2
- harfbuzz=1.4.3=0
- hdf5=1.8.17=11
- icu=58.1=1
- ipykernel=4.6.1=py35_0
- jasper=1.900.1=4
- libjpeg-turbo=1.5.1=0
- libpng=1.6.28=0
- libwebp=0.5.2=7
- libxcb=1.12=1
- matplotlib=2.0.2=np112py35_0
- numpy=1.12.1=py35_blas_openblas_200
- openblas=0.2.19=2
- pango=1.40.4=0
- pyparsing=2.2.0=py35_0
- pyqt=5.6.0=py35_3
- python-dateutil=2.6.0=py35_0
- pytz=2017.2=py35_0
- qt=5.6.2=3
- scipy=0.19.0=np112py35_blas_openblas_200
- sip=4.18=py35_1
- six=1.10.0=py35_1
- tornado=4.5.1=py35_0
- x264=20131217=3
- xorg-kbproto=1.0.7=1
- xorg-libx11=1.6.4=6
- xorg-libxau=1.0.8=3
- xorg-libxdmcp=1.1.2=3
- xorg-xproto=7.0.31=6
- bleach=1.5.0=py35_0
- decorator=4.0.11=py35_0
- entrypoints=0.2.2=py35_1
- html5lib=0.999=py35_0
- ipython=6.1.0=py35_0
- ipython_genutils=0.2.0=py35_0
- ipywidgets=6.0.0=py35_0
- jbig=2.1=0
- jedi=0.10.2=py35_2
- jinja2=2.9.6=py35_0
- jpeg=9b=0
- jsonschema=2.6.0=py35_0
- jupyter=1.0.0=py35_3
- jupyter_client=5.0.1=py35_0
- jupyter_console=5.1.0=py35_0
- jupyter_core=4.3.0=py35_0
- libffi=3.2.1=1
- libgfortran=3.0.0=1
- libiconv=1.14=0
- libsodium=1.0.10=0
- libtiff=4.0.6=3
- libxml2=2.9.4=0
- markupsafe=0.23=py35_2
- mistune=0.7.4=py35_0
- mkl=2017.0.1=0
- nbconvert=5.2.1=py35_0
- nbformat=4.3.0=py35_0
- notebook=5.0.0=py35_0
- openssl=1.0.2l=0
- pandocfilters=1.4.1=py35_0
- path.py=10.3.1=py35_0
- pcre=8.39=1
- pexpect=4.2.1=py35_0
- pickleshare=0.7.4=py35_0
- pip=9.0.1=py35_1
- pixman=0.34.0=0
- plotly=2.0.9=py35_0
- prompt_toolkit=1.0.14=py35_0
- ptyprocess=0.5.1=py35_0
- pygments=2.2.0=py35_0
- python=3.5.3=1
- pyzmq=16.0.2=py35_0
- qtconsole=4.3.0=py35_0
- readline=6.2=2
- requests=2.14.2=py35_0
- setuptools=27.2.0=py35_0
- simplegeneric=0.8.1=py35_1
- sqlite=3.13.0=0
- terminado=0.6=py35_0
- testpath=0.3.1=py35_0
- tk=8.5.18=0
- traitlets=4.3.2=py35_0
- wcwidth=0.1.7=py35_0
- wheel=0.29.0=py35_0
- widgetsnbextension=2.0.0=py35_0
- xz=5.2.2=1
- zeromq=4.1.5=0
- zlib=1.2.8=3
- ffmpeg-feature=1.0=1
- gtk2=2.24.31=2
- gtk2-feature=1.0=1
- opencv=3.2.0=np112py35_ffmpeg_gtk2_5
- v4l-utils=1.12.5=1
- atk=2.18.0=0
- gdk-pixbuf=2.32.2=1
- pip:
  - astroid==1.5.3
  - atari-py==0.0.21
  - attrs==17.2.0
  - autobahn==17.5.1
  - automat==0.6.0
  - certifi==2017.4.17
  - chardet==3.0.4
  - constantly==15.1.0
  - docker-py==1.10.3
  - docker-pycreds==0.2.1
  - fastzbarlight==0.0.14
  - go-vncdriver==0.4.19
  - gym==0.7.3
  - idna==2.5
  - incremental==17.5.0
  - ipython-genutils==0.2.0
  - isort==4.2.15
  - jupyter-client==5.0.1
  - jupyter-console==5.1.0
  - jupyter-core==4.3.0
  - lazy-object-proxy==1.3.1
  - mccabe==0.6.1
  - olefile==0.44
  - pandas==0.20.2
  - pillow==4.1.1
  - prompt-toolkit==1.0.14
  - protobuf==3.3.0
  - pycodestyle==2.3.1
  - pydocstyle==2.0.0
  - pydotplus==2.0.2
  - pyflakes==1.5.0
  - pyglet==1.2.4
  - pylama==7.3.3
  - pylama-pylint==3.0.1
  - pylint==1.7.1
  - pyopengl==3.1.0
  - pyyaml==3.12
  - scikit-learn==0.18.1
  - sklearn==0.0
  - snowballstemmer==1.2.1
  - tensorflow-gpu==1.1.0
  - tqdm==4.14.0
  - twisted==17.1.0
  - txaio==2.7.1
  - ujson==1.35
  - universe==0.21.3
  - urllib3==1.21.1
  - websocket-client==0.40.0
  - werkzeug==0.12.2
  - wrapt==1.10.10
  - zope.interface==4.4.1
prefix: /home/william/anaconda3/envs/humanrl

